In [ ]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
##sentence
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'yyour vedios are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'yyour vedios are good']

In [4]:
#define the vocabulary size
voc_size=10000

In [5]:
### One hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3105, 2914, 3616, 9491],
 [3105, 2914, 3616, 63],
 [3105, 8479, 3616, 6631],
 [9283, 5920, 4055, 1506, 7485],
 [9283, 5920, 4055, 1506, 7290],
 [8052, 3105, 3811, 3616, 4778],
 [1565, 4563, 7314, 1506]]

In [7]:
##word embedding representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs= pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3105 2914 3616 9491]
 [   0    0    0    0 3105 2914 3616   63]
 [   0    0    0    0 3105 8479 3616 6631]
 [   0    0    0 9283 5920 4055 1506 7485]
 [   0    0    0 9283 5920 4055 1506 7290]
 [   0    0    0 8052 3105 3811 3616 4778]
 [   0    0    0    0 1565 4563 7314 1506]]


In [10]:
##feature representation
dim=10

In [20]:
model=Sequential()
model.add(Embedding(voc_size, dim ,input_length=sent_length))

model.compile('adam','mse')

In [19]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [21]:
model.predict(embedded_docs)  

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step


array([[[-1.64994486e-02, -8.99449736e-03,  4.37364914e-02,
         -3.65264192e-02,  1.23187900e-02,  4.32262570e-03,
          3.45054977e-02, -1.48096904e-02,  4.76730503e-02,
          3.59222554e-02],
        [-1.64994486e-02, -8.99449736e-03,  4.37364914e-02,
         -3.65264192e-02,  1.23187900e-02,  4.32262570e-03,
          3.45054977e-02, -1.48096904e-02,  4.76730503e-02,
          3.59222554e-02],
        [-1.64994486e-02, -8.99449736e-03,  4.37364914e-02,
         -3.65264192e-02,  1.23187900e-02,  4.32262570e-03,
          3.45054977e-02, -1.48096904e-02,  4.76730503e-02,
          3.59222554e-02],
        [-1.64994486e-02, -8.99449736e-03,  4.37364914e-02,
         -3.65264192e-02,  1.23187900e-02,  4.32262570e-03,
          3.45054977e-02, -1.48096904e-02,  4.76730503e-02,
          3.59222554e-02],
        [ 3.87353040e-02,  4.99563105e-02, -4.84557636e-02,
         -3.94227616e-02,  1.38819255e-02, -1.86580904e-02,
         -5.26763126e-03, -4.93184477e-03,  4.043705